# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

sudo: false

services:
  - mysql

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
env:
  global:
    - MEDIAWIKI_VERSION=1.28.0
  matrix:
    - IS_LABS=1
    - IS_LABS=0

matrix:
  # Only test both IS_LABS values on 5.5, because that's what Labs uses.
  exclude:
    - php: 5.6
      env: IS_LABS=1
    - php: 7.0
      env: IS_LABS=1

before_install:
  - pip install --user codecov

install:
  - xtools_utilities/install-mediawiki.sh
  - composer install
  - 'sed -i "s/database_user: .*/database_user: root/" app/config/parameters.yml'
  - 'sed -i "s/database_password: .*/database_password: ~/" app/config/parameters.yml'
  - 'sed -i "s/apps.is_labs: .*/apps.is_labs: $IS_LABS/" app/config/parameters.yml'
  - php -S localhost:8081 -t build/mediawiki >/dev/null 2>&1 &

script:
  - cd "$TRAVIS_BUILD_DIR"
  - composer validate
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
  - codecov
  - ./vendor/bin/phpcs -s .

