# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
env:
  - IS_LABS=0

before_install:
  - pip install --user codecov
  - sudo apt install doxygen graphviz

install:
  - composer install
  - 'sed -i "s/app.is_labs: .*/app.is_labs: $IS_LABS/" app/config/parameters.yml'

script:
  # Quickest things first.
  - composer validate
  - ./vendor/bin/parallel-lint --exclude vendor .
  # Testing and code coverage.
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
  - codecov
  # PSR2 coding standards.
  - ./vendor/bin/phpcs -s .
  # Generate Doxygen docs, and fail if there's any error output.
  - doxygen doxygen.conf 2> >(tee doxygen.err >&2)
  - test ! -s doxygen.err

sudo: true

matrix:
  # Only test both IS_LABS values on 5.5, because that's what Labs uses.
  exclude:
    - php: 5.6
      env: IS_LABS=1
    - php: 7.0
      env: IS_LABS=1

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-xtools"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"