parameters:
  assessments:
    ar.wikipedia.org:
      wikiproject_prefix: 'ويكيبيديا:مشروع ويكي '
      class:
        م.مخ: # Featured
          badge: 'b/b4/Symbol_star_gold.svg'
          color: '#6699ff'
          category: 'تصنيف:مقالات ذات صنف م.مخ'
        أ: # A
          badge: '2/25/Symbol_a_class.svg'
          color: '#66ffff'
          category: 'تصنيف:مقالات ذات صنف أ'
        م.ج: # GA
          badge: '9/9d/Symbol_star_silver.svg'
          color: '#66ff66'
          category: 'تصنيف:مقالات ذات صنف م.ج'
        ب+: # B+
          badge: '2/2c/Symbol_bplus_class.svg'
          color: '#66ff66'
          category: 'تصنيف:مقالات ذات صنف ب+'
        ب: # B
          badge: '5/5f/Symbol_b_class.svg'
          color: '#b2ff66'
          category: 'تصنيف:مقالات ذات صنف ب'
        ج: # C
          badge: 'e/e6/Symbol_c_class.svg'
          color: '#ffff66'
          category: 'تصنيف:مقالات ذات صنف ج'
        بداية: # Start
          badge: 'a/a4/Symbol_start_class.svg'
          color: '#ffaa66'
          category: 'تصنيف:مقالات ذات صنف بداية'
        بذرة: # Stub
          badge: 'f/f5/Symbol_stub_class.svg'
          color: '#ff6666'
          category: 'تصنيف:مقالات ذات صنف بذرة'
        ق.مخ: # FL
          badge: 'b/bc/Featured_article_star.svg'
          color: '#6699ff'
          category: 'تصنيف:مقالات ذات صنف ق.مخ'
        قائمة: # List
          badge: 'd/db/Symbol_list_class.svg'
          color: '#aa88ff'
          category: 'تصنيف:مقالات ذات صنف قائمة'
        ب.قائمة: # B-List
          badge: 'd/db/Symbol_list_class.svg'
          color: '#ff6666'
          category: 'تصنيف:مقالات ذات صنف ب.قائمة'
        م.ف.م: # M.F. ???
          badge: 'd/d5/Desacuerdo-Artículo bueno-blue.svg'
          color: '#ccaaff'
          category: 'تصنيف:مقالات ذات صنف م.ف.م'
        حالية: # Current ???
          badge: '5/54/Symbol_wait.svg'
          color: '#d870ff'
          category: 'تصنيف:مقالات ذات صنف حالية'
        مستقبلية: # Future ???
          badge: '0/04/Symbol_wait_alternative.svg'
          color: '#8a95c9'
          category: 'تصنيف:مقالات ذات صنف مستقبلية'
        تصنيف: # Category
          badge: '9/96/Symbol_category_class.svg'
          color: '#ffdb58'
          category: 'تصنيف:مقالات ذات صنف تصنيف'
        توضيح: # Disambig
          badge: '2/2a/Symbol_dab_class.svg'
          color: '#00fa9a'
          category: 'تصنيف:مقالات ذات صنف توضيح'
        و.مخ: # Featured file
          badge: 'b/bc/Featured_article_star.svg'
          color: '#6699ff'
          category: 'تصنيف:مقالات ذات صنف و.مخ'
        ملف: # File
          badge: '9/9c/Symbol_file_class.svg'
          color: '#ddccff'
          category: 'تصنيف:مقالات ذات صنف ملف'
        دمج: # Merge ???
          badge: 'b/b0/Symbol_merge_vote.svg'
          color: '#add8e6'
          category: 'تصنيف:مقالات ذات صنف دمج'
        بوابة: # Portal
          badge: 'e/e2/Symbol_portal_class.svg'
          color: '#cc8899'
          category: 'تصنيف:مقالات ذات صنف بوابة'
        مشروع: # WikiProject
          badge: '7/72/Symbol_project_class.svg'
          color: '#c0c090'
          category: 'تصنيف:مقالات ذات صنف مشروع'
        تحويلة: # Converted ???
          badge: '4/48/Symbol_deferred_class.svg'
          color: '#c0c0c0'
          category: 'تصنيف:مقالات أغنية الجليد والنار ذات صنف تحويلة'
        قالب: # Template
          badge: '5/5c/Symbol_template_class.svg'
          color: '#fbceb1'
          category: 'تصنيف:مقالات ذات صنف قالب'
        غير مقالية: # Uncategorized ???
          badge: '1/11/Symbol_question_vote.svg'
          color: '#f5f5f5'
          category: 'تصنيف:مقالات ذات صنف غير مقالية'
        Unknown:
          badge: 'e/e0/Symbol_question.svg'
          color: ''
          category: 'تصنيف:مقالات غير مقيمة'
      importance:
        فائقة: # High
          color: '#ff00ff'
          category: 'تصنيف:مقالات فائقة الأهمية'
          weight: 5
        عالية: # Top
          color: '#ff88ff'
          category: 'تصنيف:مقالات عالية الأهمية'
          weight: 4
        متوسطة: # Medium
          color: '#ffbbff'
          category: 'تصنيف:مقالات متوسطة الأهمية'
          weight: 3
        قليلة: # Low
          color: '#ffddff'
          category: 'تصنيف:مقالات قليلة الأهمية'
          weight: 2
        غير مطبقة: # Lowest
          color: '#f5f5f5'
          category: 'تصنيف:مقالات غير مطبقة الأهمية'
          weight: 1
        Unknown:
          color: ''
          category: 'تصنيف:مقالات غير معروفة الأهمية'
          weight: 0
    en.wikipedia.org:
      wikiproject_prefix: 'Wikipedia:WikiProject '
      class:
        FA:
          badge: 'b/bc/Featured_article_star.svg'
          color: '#6699ff'
          category: 'Category:FA-Class articles'
        A:
          badge: '2/25/Symbol_a_class.svg'
          color: '#66ffff'
          category: 'Category:A-Class articles'
        GA:
          badge: '9/94/Symbol_support_vote.svg'
          color: '#66ff66'
          category: 'Category:GA-Class articles'
        B:
          badge: '5/5f/Symbol_b_class.svg'
          color: '#b2ff66'
          category: 'Category:B-Class articles'
        C:
          badge: 'e/e6/Symbol_c_class.svg'
          color: '#ffff66'
          category: 'Category:C-Class articles'
        Start:
          badge: 'a/a4/Symbol_start_class.svg'
          color: '#ffaa66'
          category: 'Category:Start-Class articles'
        Stub:
          badge: 'f/f5/Symbol_stub_class.svg'
          color: '#ff6666'
          category: 'Category:Stub-Class articles'
        FL:
          badge: 'e/e7/Cscr-featured.svg'
          color: '#6699ff'
          category: 'Category:FL-Class articles'
        List:
          badge: 'd/db/Symbol_list_class.svg'
          color: '#aa88ff'
          category: 'Category:List-Class articles'
        Disambig:
          badge: '2/2a/Symbol_dab_class.svg'
          color: '#00fa9a'
          category: 'Category:Disambig-Class articles'
        Redirect:
          badge: 'a/a2/Symbol_redirect_class.svg'
          color: '#c0c0c0'
          category: 'Category:Redirect-Class articles'
        Book:
          badge: '4/4d/Symbol_book_class.svg'
          color: '#98FF98'
          category: 'Category:Book-Class articles'
        Template:
          badge: '5/5c/Symbol_template_class.svg'
          color: '#fbceb1'
          category: 'Category:Template-Class articles'
        Category:
          badge: '9/96/Symbol_category_class.svg'
          color: '#ffdb58'
          category: 'Category:Category-Class articles'
        Unknown:
          badge: 'e/e0/Symbol_question.svg'
          color: ''
          category: 'Category:Unassessed articles'
      importance:
        Top:
          color: '#ff00ff'
          category: 'Category:Top-importance articles'
          weight: 5
        High:
          color: '#ff88ff'
          category: 'Category:Top-importance articles'
          weight: 4
        Mid:
          color: '#ffbbff'
          category: 'Category:Top-importance articles'
          weight: 3
        Low:
          color: '#ffddff'
          category: 'Category:Top-importance articles'
          weight: 2
        Bottom:
          color: '#ffeeff'
          category: 'Category:Top-importance articles'
          weight: 1
        Unknown:
          color: ''
          category: 'Category:Unknown-importance articles'
          weight: 0
    tr.wikipedia.org:
      wikiproject_prefix: 'Vikiproje:'
      class:
        SM:
          badge: 'b/bc/Featured_article_star.svg'
          color: '#6699ff'
          category: 'Kategori:SM-sınıf Vikiproje sayfaları'
        KM:
          badge: 'e/eb/Cscr-featured2.png'
          color: '#66ff66'
          category: 'Kategori:KM-sınıf Vikiproje sayfaları'
        B:
          badge: '5/5f/Symbol_b_class.svg'
          color: '#b2ff66'
          category: 'Kategori:Vikiproje 10K Az-önemli B-sınıf sayfalar'
        C:
          badge: 'e/e6/Symbol_c_class.svg'
          color: '#ffff66'
          category: 'Kategori:C-sınıf Vikiproje sayfaları'
        Başlangıç:
          badge: 'a/a4/Symbol_start_class.svg'
          color: '#ffaa66'
          category: 'Kategori:Başlangıç-sınıf Vikiproje sayfaları'
        Taslak:
          badge: 'f/f5/Symbol_stub_class.svg'
          color: '#eb6163'
          category: 'Kategori:Taslak-sınıf Vikiproje sayfaları'
        SL:
          badge: 'b/bc/Featured_article_star.svg'
          color: '#6699ff'
          category: 'Kategori:Vikiproje Afrika SL-sınıf sayfalar'
        Liste:
          badge: 'd/db/Symbol_list_class.svg'
          color: '#aa88ff'
          category: 'Kategori:Liste-sınıf Vikiproje sayfaları'
        Anlam ayrımı:
          badge: '2/2a/Symbol_dab_class.svg'
          color: '#00fa9a'
          category: 'Kategori:Anlam ayrımı-sınıf Vikiproje sayfaları'
        Yönlendirme:
          badge: '8/89/Symbol_redirect_vote2.svg'
          color: '#c0c0c0'
          category: 'Kategori:Yönlendirme-sınıf Vikiproje sayfaları'
        Şablon:
          badge: '5/5c/Symbol_template_class.svg'
          color: '#fbceb1'
          category: 'Kategori:Şablon-sınıf Vikiproje sayfaları'
        Kategori:
          badge: '4/48/Folder_Hexagonal_Icon.svg'
          color: '#ffdb58'
          category: 'Kategori:Kategori-sınıf Vikiproje sayfaları'
        Dosya:
          badge: 'e/e7/Video-x-generic.svg'
          color: '#ddccff'
          category: 'Kategori:Dosya-sınıf Vikiproje sayfaları'
        Unknown:
          badge: 'e/e0/Symbol_question.svg'
          color: ''
          category: 'Kategori:Değerlendirilmemiş-sınıf Vikiproje sayfaları'
      importance:
        En:
          color: '#ff00ff'
          category: 'Kategori:En-önemli Vikiproje sayfaları'
          weight: 4
        Çok:
          color: '#ff88ff'
          category: 'Kategori:Çok-önemli Vikiproje sayfaları'
          weight: 3
        Orta:
          color: '#ffbbff'
          category: 'Kategori:Orta-önemli Vikiproje sayfaları'
          weight: 2
        Az:
          color: '#ffddff'
          category: 'Kategori:Az-önemli Vikiproje sayfaları'
          weight: 1
        Unknown:
          color: ''
          category: 'Category:Unknown-importance articles'
          weight: 0
