parameters:
  rfa:
    tilda_wiki_p:
      rfa_namespace: 4
      sections:
        - "support"
        - "oppose"
        - "neutral"
        - "comments"
      pages:
        rfa: "Project:Requests for Adminship"
        rfb: "Project:Requests for bureaucratship"
