parameters:
  automated_tools:
    Rollback: '^(\[\[Help:Reverting\|Reverted\]\]|Reverted) edits by \[\[Special:(Contribs|Contributions)\/.*?\|.*?\]\] \(\[\[User talk:.*?\|talk\]\]\) to last version by .*'
    Undo: '^Undid revision \d+ by \[\[Special:(Contribs|Contributions)\/.*?\|.*?\]\]'
    Pending changes revert: '^(\[\[Help:Reverting\|Reverted\]\]|Reverted) \d+ (\[\[Wikipedia:Pending changes\|pending\]\]|pending) edits? (to revision \d+|by \[\[Special:(Contribs|Contributions)\/.*?\|.*?\]\])'
    Bot revert: '^Reverting possible vandalism by.*?to version by|^BOT (Reverted edits by|rv \[\[Special:Contributions)'
    Page move: '^.*?moved page \[\[(?!.*?WP:AFCH)|moved \[\[.*?\]\] to \[\['
    Page curation: 'using \[\[Wikipedia:Page Curation\|Page Curation'
    Twinkle: 'WP:(TW|TWINKLE|Twinkle)|WP:FRIENDLY|Wikipedia:Twinkle'
    Huggle: 'WP:HG'
    STiki: 'WP:STiki|WP:STIKI'
    Igloo: 'Wikipedia:Igloo'
    Popups: 'Wikipedia:Tools\/Navigation_popups|popups'
    AFCH: 'WP:AFCH|WP:AFCHRW'
    AWB: 'Wikipedia:AWB|WP:AWB|Project:AWB'
    WPCleaner: 'WP:CLEANER|\[\[\Wikipedia:DPL|\[\[WP:WCW\]\] project \('
    HotCat: 'using \[\[(WP:HOTCAT|WP:HC|Help:Gadget-HotCat)\|HotCat'
    reFill: 'User:Zhaofeng Li\/Reflinks|WP:REFILL'
    Checklinks: 'using \[\[w:WP:CHECKLINKS\|Checklinks'
    Dab solver: 'using \[\[(tools:~dispenser\/view\/Dab_solver|WP:DABSOLVER)\|Dab solver|(Disambiguated|Unlinked|Help needed): \[\[|Disambiguated \d+ links|Repaired link.*?\[\[Wikipedia:WikiProject Disambiguation\|please help'
    Dabfix: 'using \[\[tools:~dispenser\/cgi-bin\/dabfix.py'
    Reflinks: '\[\[(tools:~dispenser\/view\/Reflinks|WP:REFLINKS)\|Reflinks'
    WikiPatroller: 'User:Jfmantis\/WikiPatroller'
    delsort: 'Wikipedia:WP:FWDS|WP:FWDS|User:APerson\/delsort\|delsort.js|User:Enterprisey\/delsort\|assisted'
    Ohconfucius script: '\[\[(User:Ohconfucius\/.*?|WP:MOSNUMscript)\|script'
    OneClickArchiver: '\[\[(User:Equazcion\/OneClickArchiver|User:Technical 13\/1CA)\|OneClickArchiver'
    editProtectedHelper: 'WP:EPH|EPH'
    WikiLove: 'new WikiLove message'
    AutoEd: 'using \[\[(Wikipedia|WP):AutoEd\|AutoEd'
    Mike's Wiki Tool: 'using \[\[User:MichaelBillington\/MWT\|MWT'
    Global replace: '\(\[\[c:GR\|GR\]\]\) '
    Admin actions: '^(Protected|Changed protection).*?\[[Ee]dit=|^Removed protection from|^Configured pending changes.*?\[[Aa]uto-accept|^Reset pending changes settings'
    CSD Helper: '\(\[\[User:Ale_jrb\/Scripts\|CSDH'
    Find link: 'using \[\[User:Edward\/Find link\|Find link'
    responseHelper: '\(using \[\[User:MusikAnimal\/responseHelper\|responseHelper'
    Advisor.js: '\(using \[\[User:Cameltrader#Advisor.js\|Advisor.js'
    AfD closures: '^\[\[Wikipedia:Articles for deletion\/.*?closed as'
    Sagittarius: '\(\[\[User:Kephir\/gadgets\/sagittarius\|'
    Redirect: '\[\[WP:AES\|←\]\]Redirected page to \[\[.*?\]\]'
    Dashes: 'using a \[\[User:GregU\/dashes.js\|script'
    SPI Helper: '^(Archiving case (to|from)|Adding sockpuppetry (tag|block notice) per) \[\[Wikipedia:Sockpuppet investigations'
    User:Doug/closetfd.js: '\(using \[\[User:Doug\/closetfd.js'
    Cat-a-lot: '^\[\[Help:Cat-a-lot\|Cat-a-lot\]\]:'
    autoFormatter: 'using (\[\[:meta:User:TMg\/autoFormatter|autoFormatter)'
    Citation bot: '\[\[WP:UCB\|Assisted by Citation bot'
    Red Link Recovery Live: '\[\[w:en:WP:RLR\|You can help!'
    Script Installer: '\[\[User:Equazcion\/ScriptInstaller\|Script Installer'
    findargdups: '\[\[:en:User:Frietjes\/findargdups'
    closemfd.js: '\(using \[\[User:Doug\/closemfd.js'
    DisamAssist: 'using \[\[User:Qwertyytrewqqwerty\/DisamAssist'
    Vada: '\(\[\[WP:Vada\]\]\)'
    stubtagtab.js: 'using \[\[User:MC10\/stubtagtab.js'
    AutoSpell: 'User:Symplectic_Map\/AutoSpell\|Script-assisted'
    Draftify: '\(\[\[WP:DFY\|DFY\]\]\)'
    AFC/R HS: 'Using \[\[User:PhantomTech\/scripts\/AFCRHS.js\|AFC\/R HS'
    For the Common Good: 'WP:FTCG\|FtCG'
    Twinkle revert: '(Reverted to revision|Reverted \d+ edits).*(WP:(TW|TWINKLE|Twinkle)|Wikipedia:Twinkle)'
    User:Technical13/Scripts/OrphanStatus.js: '\[\[User:Technical_13/Scripts/OrphanStatus\|'
    The Wikipedia Adventure: 'simulated automatically as part of \[\[WP:The Wikipedia Adventure\|'

  semi-automated edits source: https://tools.wmflabs.org/musikanimal/nonautomated_edits/about
