# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ["@service_container", "@request_stack", "@session"]
        public: false
        tags:
            - { name: twig.extension }
    app.wiki_extension:
        class: AppBundle\Twig\WikiExtension
        arguments: ["@service_container", "@request_stack", "@session"]
        public: false
        tags:
            - { name: twig.extension }
    app.api_helper:
        class: AppBundle\Helper\ApiHelper
        arguments: ["@service_container"]
        public: true
        tags:
          - {name: api.helper}
    app.labs_helper:
        class: AppBundle\Helper\LabsHelper
        arguments: ["@service_container"]
        public: true
        tags:
          - {name: labs.helper}
    app.pageviews_helper:
        class: AppBundle\Helper\PageviewsHelper
        arguments: ["@service_container"]
        public: true
        tags:
          - {name: pageviews.helper}
    app.automated_edits_helper:
        class: AppBundle\Helper\AutomatedEditsHelper
        arguments: ["@service_container"]
        public: true
        tags:
          - {name: automatededits.helper}
