parameters:
  tools:
    ec: ec
    articleinfo: articleinfo
    pages: pages
    topedits: topedits
    blame: blame
    autoedits: autoedits
    adminstats: adminstats
    adminscore: adminscore
    rfa: rfa
    rfap: rfap
    bash: bash
    sc: sc