parameters:
  tools:
    ec: ec
    articleinfo: articleinfo
    pages: pages
    topedits: topedits
    rangecontribs: rangecontribs
    blame: blame
    autoedits: autoedits
    autoblock: autoblock
    adminstats: adminstats
    adminscore: adminscore
    rfa: rfa
    rfab: rfab
    bash: bash
    sc: sc